name: flutter_paypal_checkout
description: Best and easy way to INTEGRATE PayPal checkout in Flutter application
version: 1.0.0
# homepage:

environment:
  sdk: ">=2.18.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
